# Generated by Django 4.2.2 on 2023-06-09 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boletos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreBoleto', models.CharField(max_length=100)),
                ('Precio', models.FloatField(max_length=100000)),
                ('CantidadBoletos', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=10000)),
                ('Fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
