# Generated by Django 4.2.2 on 2023-06-23 00:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=10000)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Boletos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField(max_length=100000)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('eventos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiBoletos.eventos')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
