# Generated by Django 4.2.2 on 2023-06-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boletos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreBoleto', models.CharField(max_length=100)),
                ('NombreEvento', models.CharField(max_length=100)),
                ('CantidadBoletos', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
